-- =========================
-- Master tables
-- =========================

CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT        NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE suppliers
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT        NOT NULL,
    contact_person TEXT,
    phone          TEXT        NOT NULL,
    email          TEXT,
    website        TEXT,
    address        TEXT,
    tax_number     TEXT,
    payment_terms  TEXT        NOT NULL DEFAULT 'Net 30',
    status         TEXT        NOT NULL DEFAULT 'Active'
        CHECK (status IN ('Active', 'Inactive')),
    is_preferred   BOOLEAN     NOT NULL DEFAULT FALSE,
    notes          TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT        NOT NULL UNIQUE,
    full_name     TEXT        NOT NULL,
    email         TEXT,
    password_hash TEXT        NOT NULL,
    role          TEXT        NOT NULL DEFAULT 'Cashier'
        CHECK (role IN ('Admin', 'Pharmacist', 'Cashier', 'Viewer')),
    status        TEXT        NOT NULL DEFAULT 'Active'
        CHECK (status IN ('Active', 'Inactive')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    phone      TEXT,
    email      TEXT,
    notes      TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE medicines
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   TEXT           NOT NULL,
    brand                  TEXT           NOT NULL,
    category_id            BIGINT         NOT NULL REFERENCES categories (id) ON DELETE RESTRICT,
    unit                   TEXT           NOT NULL,
    barcode                TEXT UNIQUE,
    status                 TEXT           NOT NULL DEFAULT 'Active'
        CHECK (status IN ('Active', 'Inactive', 'Expired')),
    description            TEXT,
    default_purchase_price NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (default_purchase_price >= 0),
    default_sell_price     NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (default_sell_price >= 0),
    reorder_level          INTEGER        NOT NULL DEFAULT 10 CHECK (reorder_level >= 0),
    tax_rate               NUMERIC(5, 2)  NOT NULL DEFAULT 0 CHECK (tax_rate >= 0),
    requires_prescription  BOOLEAN        NOT NULL DEFAULT FALSE,
    allow_fractional_qty   BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (name, brand)
);

CREATE INDEX idx_medicines_name ON medicines (name);
CREATE INDEX idx_medicines_barcode ON medicines (barcode);
CREATE INDEX idx_medicines_category_id ON medicines (category_id);
CREATE INDEX idx_medicines_status ON medicines (status);

CREATE TABLE batches
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id      BIGINT         NOT NULL REFERENCES medicines (id) ON DELETE RESTRICT,
    batch_number     TEXT           NOT NULL,
    quantity_on_hand NUMERIC(12, 3) NOT NULL DEFAULT 0 CHECK (quantity_on_hand >= 0),
    purchase_price   NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (purchase_price >= 0),
    sell_price       NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (sell_price >= 0),
    manufacture_date DATE,
    expiry_date      DATE           NOT NULL,
    supplier_id      BIGINT         REFERENCES suppliers (id) ON DELETE SET NULL,
    storage_location TEXT,
    notes            TEXT,
    status           TEXT           NOT NULL DEFAULT 'Active'
        CHECK (status IN ('Active', 'Expired', 'Depleted')),
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (medicine_id, batch_number)
);

CREATE INDEX idx_batches_medicine_id ON batches (medicine_id);
CREATE INDEX idx_batches_expiry_date ON batches (expiry_date);
CREATE INDEX idx_batches_status ON batches (status);
CREATE INDEX idx_batches_supplier_id ON batches (supplier_id);

-- =========================
-- Sales
-- =========================

CREATE TABLE sales
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_number      TEXT           NOT NULL UNIQUE,
    customer_id      BIGINT         REFERENCES customers (id) ON DELETE SET NULL,
    user_id          BIGINT         NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    subtotal         NUMERIC(12, 2) NOT NULL DEFAULT 0,
    tax_amount       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount_percent NUMERIC(5, 2)  NOT NULL DEFAULT 0,
    discount_amount  NUMERIC(12, 2) NOT NULL DEFAULT 0,
    grand_total      NUMERIC(12, 2) NOT NULL DEFAULT 0,
    payment_method   TEXT           NOT NULL DEFAULT 'Cash'
        CHECK (payment_method IN ('Cash', 'Card', 'Mobile', 'Credit', 'Other')),
    cash_tendered    NUMERIC(12, 2),
    change_amount    NUMERIC(12, 2),
    card_reference   TEXT,
    notes            TEXT,
    status           TEXT           NOT NULL DEFAULT 'Completed'
        CHECK (status IN ('Completed', 'Voided', 'Held')),
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sales_sale_number ON sales (sale_number);
CREATE INDEX idx_sales_created_at ON sales (created_at);
CREATE INDEX idx_sales_user_id ON sales (user_id);
CREATE INDEX idx_sales_customer_id ON sales (customer_id);
CREATE INDEX idx_sales_status ON sales (status);

CREATE TABLE sale_items
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id          BIGINT         NOT NULL REFERENCES sales (id) ON DELETE CASCADE,
    medicine_id      BIGINT         NOT NULL REFERENCES medicines (id) ON DELETE RESTRICT,
    batch_id         BIGINT         NOT NULL REFERENCES batches (id) ON DELETE RESTRICT,
    quantity         NUMERIC(12, 3) NOT NULL CHECK (quantity > 0),
    unit_price       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount_percent NUMERIC(5, 2)  NOT NULL DEFAULT 0,
    line_total       NUMERIC(12, 2) NOT NULL DEFAULT 0
);

CREATE INDEX idx_sale_items_sale_id ON sale_items (sale_id);
CREATE INDEX idx_sale_items_medicine_id ON sale_items (medicine_id);
CREATE INDEX idx_sale_items_batch_id ON sale_items (batch_id);

CREATE TABLE held_sales
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_number TEXT        NOT NULL,
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    items_json  JSONB       NOT NULL,
    notes       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- Purchasing
-- =========================

CREATE TABLE purchase_orders
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number              TEXT           NOT NULL UNIQUE,
    supplier_id            BIGINT         NOT NULL REFERENCES suppliers (id) ON DELETE RESTRICT,
    status                 TEXT           NOT NULL DEFAULT 'Draft'
        CHECK (status IN ('Draft', 'Submitted', 'Received', 'Cancelled')),
    expected_delivery_date DATE,
    notes                  TEXT,
    subtotal               NUMERIC(12, 2) NOT NULL DEFAULT 0,
    tax_amount             NUMERIC(12, 2) NOT NULL DEFAULT 0,
    grand_total            NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    received_at            TIMESTAMPTZ
);

CREATE INDEX idx_po_supplier_id ON purchase_orders (supplier_id);
CREATE INDEX idx_po_status ON purchase_orders (status);
CREATE INDEX idx_po_created_at ON purchase_orders (created_at);

CREATE TABLE purchase_order_items
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT         NOT NULL REFERENCES purchase_orders (id) ON DELETE CASCADE,
    medicine_id       BIGINT         NOT NULL REFERENCES medicines (id) ON DELETE RESTRICT,
    unit              TEXT           NOT NULL,
    qty_ordered       NUMERIC(12, 3) NOT NULL DEFAULT 0,
    qty_received      NUMERIC(12, 3) NOT NULL DEFAULT 0,
    unit_cost         NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal          NUMERIC(12, 2) NOT NULL DEFAULT 0
);

CREATE INDEX idx_poi_po_id ON purchase_order_items (purchase_order_id);
CREATE INDEX idx_poi_medicine_id ON purchase_order_items (medicine_id);

-- =========================
-- Rules / settings / audit
-- =========================

CREATE TABLE reorder_rules
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id   BIGINT REFERENCES categories (id) ON DELETE CASCADE,
    reorder_level INTEGER NOT NULL DEFAULT 10,
    reorder_qty   INTEGER NOT NULL DEFAULT 50,
    alert_method  TEXT    NOT NULL DEFAULT 'Dashboard'
        CHECK (alert_method IN ('Dashboard', 'Email', 'Both')),
    UNIQUE (category_id)
);

CREATE TABLE settings
(
    key        TEXT PRIMARY KEY,
    value      TEXT        NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stock_movements
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id      BIGINT         NOT NULL REFERENCES batches (id) ON DELETE RESTRICT,
    movement_type TEXT           NOT NULL
        CHECK (movement_type IN ('RECEIPT', 'SALE', 'RETURN', 'ADJUSTMENT', 'VOID_RESTORE')),
    qty_delta     NUMERIC(12, 3) NOT NULL,
    unit_cost     NUMERIC(12, 2),
    ref_type      TEXT,
    ref_id        BIGINT,
    note          TEXT,
    created_by    BIGINT         REFERENCES users (id) ON DELETE SET NULL,
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_stock_movements_batch_id ON stock_movements (batch_id);
CREATE INDEX idx_stock_movements_created_at ON stock_movements (created_at);

CREATE TABLE audit_log
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    action_type   TEXT        NOT NULL,
    entity        TEXT        NOT NULL,
    entity_id     BIGINT,
    details       JSONB,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_log_created_at ON audit_log (created_at);